### PR TITLE
release v0.4.1

### PR DESCRIPTION
**Pull request by MarcoPolo**

### CODE REVIEW

**Comment by marten-seemann** [comment]
Now that’s annoying. Would gorelease still insist on a new minor version if we exclude the Go version bump?

**Comment by MarcoPolo** [comment]
What's the benefit of keeping it a patch release in this case?

**Comment by marten-seemann** [comment]
If it’s a minor release, the go-libp2p release will have to be another minor as well, according to semver.

**Comment by MarcoPolo** [comment]
Can I simply merge it as a patch or is there something else I should do?

**Comment by MarcoPolo** [comment]
Currently thinking this is a `gorelease` bug because this output looks identical:

```
# github.com/multiformats/go-multistream
## incompatible changes
ErrNotSupported: changed from ErrNotSupported[T StringLike] to ErrNotSupported[T StringLike]
Handler: changed from Handler[T StringLike] to Handler[T StringLike]
HandlerFunc: changed from HandlerFunc[T StringLike] to HandlerFunc[T StringLike]
MultistreamMuxer: changed from MultistreamMuxer[T StringLike] to MultistreamMuxer[T StringLike]
NewMultistreamMuxer: changed from func() *MultistreamMuxer[T] to func() *MultistreamMuxer[T]

# summary
Suggested version: v0.5.0
```

Also if you run `gorelease` from v0.4.0 branch, you'll still get the suggested version v0.5.0

**Pull request merged**
